# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solving Generalized LASSO with fixed \eqn{\lambda = 1}
NULL

genlassoRcpp <- function(Y, W, m, eta1, eta2, a, rho, max_iter, eps, truncate) {
    .Call('_CVN_genlassoRcpp', PACKAGE = 'CVN', Y, W, m, eta1, eta2, a, rho, max_iter, eps, truncate)
}

updateZRcpp <- function(m, p, Theta, Y, W, eta1, eta2, a, rho, max_iter, eps, truncate) {
    .Call('_CVN_updateZRcpp', PACKAGE = 'CVN', m, p, Theta, Y, W, eta1, eta2, a, rho, max_iter, eps, truncate)
}

