# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solving Generalized LASSO with fixed \eqn{\lambda = 1}
#' 
#' Solves efficiently the generalized LASSO problem of the form 
#' \deqn{
#'   \hat{\beta} = \text{argmin } \frac{1}{2} || y - \beta ||_2^2 + ||D\beta||_1 
#' }
#' where \eqn{\beta} and \eqn{y} are \eqn{m}-dimensional vectors and 
#' \eqn{D} is a \eqn{(c \times m)}-matrix where \eqn{c \geq m}. 
#' We solve this optimization problem using an adaption of the ADMM
#' algorithm presented in Zhu (2017). 
#'
#' @return The estimated vector \eqn{\hat{\beta}}
#'
#' @references 
#' Zhu, Y. (2017). An Augmented ADMM Algorithm With Application to the 
#' Generalized Lasso Problem. Journal of Computational and Graphical Statistics, 
#' 26(1), 195–204. https://doi.org/10.1080/10618600.2015.1114491
#' 
#' @seealso \code{\link{convertRawReports2Tables}}
aug_genlassoRcpp <- function(y, W, m, c, eta1, eta2, a, rho, max_iter, eps, truncate) {
    .Call('_CVN_aug_genlassoRcpp', PACKAGE = 'CVN', y, W, m, c, eta1, eta2, a, rho, max_iter, eps, truncate)
}

determine_steps_Rccp <- function(m) {
    invisible(.Call('_CVN_determine_steps_Rccp', PACKAGE = 'CVN', m))
}

show_indices_Rcpp <- function(m, W) {
    invisible(.Call('_CVN_show_indices_Rcpp', PACKAGE = 'CVN', m, W))
}

